PROGRAM=clax
SOURCES=$(wildcard *.c)
OBJECTS=$(SOURCES:.c=.o)
CFLAGS=-Icontrib/mbedtls -D_ALL_SOURCE
LFLAGS=
LIBS=contrib/mbedtls/*.o -lws2_32

all: mbedtls $(PROGRAM)

$(PROGRAM): $(OBJECTS)
	$(CC) $(CFLAGS) $^ $(LFLAGS) $(LIBS) -o $(PROGRAM)

mbedtls:
	$(MAKE) -C contrib/mbedtls CFLAGS="-DWINDOWS=1"

clean:
	rm -f $(PROGRAM) $(OBJECTS)
	$(MAKE) -C contrib/mbedtls clean
