CC=c99
PROGRAM=clax
SOURCES=$(wildcard *.c)
OBJECTS=$(SOURCES:.c=.o)
CFLAGS=-Icontrib/mbedtls -D_ALL_SOURCE -D__STRING_CODE_SET__="ISO8859-1" -qlanglvl=extc99
LFLAGS=
LIBS=contrib/mbedtls/*.o

all: libascii mbedtls $(PROGRAM)

libascii:
	$(MAKE) CC=c99 -C arch/zos/libascii

mbedtls:
	$(MAKE) CC=c99 -C contrib/mbedtls

$(PROGRAM): $(OBJECTS)
	$(CC) $(CFLAGS) $^ $(LFLAGS) $(LIBS) arch/zos/libascii.a

clean:
	rm -f $(PROGRAM) $(OBJECTS)
	$(MAKE) -C contrib/mbedtls clean
