on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build & Release

jobs:
  Linux_Build:
    name: Create Linux Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make libuv
        run: |
          git submodule update --init
          cd contrib/libuv
          ./autogen.sh
          ./configure
          make
      - name: Make clax
        run: |
          make
          mkdir clax-linux-${{github.ref_name}}
          cp clax LICENSE README.md clax.ini.unix.example clax-linux-${{github.ref_name}}
          tar cvzf clax-linux-${{github.ref_name}}.tgz clax-linux-${{github.ref_name}}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
             clax-linux-${{github.ref_name}}.tgz
  Windows_Build:
    name: Create Windows Release
    needs: Linux_Build
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Checkout contrib
        run: |
          git submodule update --init
      - name: Make clax
        shell: cmd
        run: |
          make -f Makefile.mingw64
          dir
          mkdir "clax-windows-${{github.ref_name}}"
          copy clax.exe "clax-windows-${{github.ref_name}}"
          copy README.md "clax-windows-${{github.ref_name}}"
          copy LICENSE "clax-windows-${{github.ref_name}}"
          copy clax.ini.win.example "clax-windows-${{github.ref_name}}"
      - name: Zip Windows Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'clax-windows-${{github.ref_name}}.zip'
          path: 'clax-windows-${{github.ref_name}}'
      - name: Upload Zip to Release
        uses: AButler/upload-release-assets@v2.0.2
        with:
          files: 'clax-windows-${{github.ref_name}}.zip'
          release-tag: ${{ github.ref_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
